# Day 1

### Importing the data 

Link to data - https://www.kaggle.com/datasets/alfathterry/bbc-full-text-document-classification?resource=download

In [52]:
import pandas as pd 
import numpy as np 

In [53]:
df = pd.read_csv('bbc_data.csv')

In [54]:
df

data         labels
0     Musicians to tackle US red tape  Musicians gro...  entertainment
1     U2s desire to be number one  U2, who have won ...  entertainment
2     Rocker Doherty in on-stage fight  Rock singer ...  entertainment
3     Snicket tops US box office chart  The film ada...  entertainment
4     Oceans Twelve raids box office  Oceans Twelve,...  entertainment
...                                                 ...            ...
2220  Warning over Windows Word files  Writing a Mic...           tech
2221  Fast lifts rise into record books  Two high-sp...           tech
2222  Nintendo adds media playing to DS  Nintendo is...           tech
2223  Fast moving phone viruses appear  Security fir...           tech
2224  Hacker threat to Apples iTunes  Users of Apple...           tech

[2225 rows x 2 columns]

In [55]:
df['labels'].unique()

array(['entertainment', 'business', 'sport', 'politics', 'tech'],
      dtype=object)

In [56]:
df['labels'].nunique()

5

In [57]:
df['data'].nunique()

2126

In [58]:
df[['data','labels']].drop_duplicates()

data         labels
0     Musicians to tackle US red tape  Musicians gro...  entertainment
1     U2s desire to be number one  U2, who have won ...  entertainment
2     Rocker Doherty in on-stage fight  Rock singer ...  entertainment
3     Snicket tops US box office chart  The film ada...  entertainment
4     Oceans Twelve raids box office  Oceans Twelve,...  entertainment
...                                                 ...            ...
2220  Warning over Windows Word files  Writing a Mic...           tech
2221  Fast lifts rise into record books  Two high-sp...           tech
2222  Nintendo adds media playing to DS  Nintendo is...           tech
2223  Fast moving phone viruses appear  Security fir...           tech
2224  Hacker threat to Apples iTunes  Users of Apple...           tech

[2126 rows x 2 columns]

In [59]:
df.isna().sum()

data      0
labels    0
dtype: int64

In [60]:
df['labels'].value_counts()

sport            511
business         510
politics         417
tech             401
entertainment    386
Name: labels, dtype: int64

In [61]:
l = [1,2.,1,8,9]

In [62]:
dir(l)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [63]:
dir(df)

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__dataframe__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex_

# Day 2

## Prepping the data 

### Converting all the text column to lower case

In [64]:
df['data'] = df['data'].str.lower()

In [65]:
df

data         labels
0     musicians to tackle us red tape  musicians gro...  entertainment
1     u2s desire to be number one  u2, who have won ...  entertainment
2     rocker doherty in on-stage fight  rock singer ...  entertainment
3     snicket tops us box office chart  the film ada...  entertainment
4     oceans twelve raids box office  oceans twelve,...  entertainment
...                                                 ...            ...
2220  warning over windows word files  writing a mic...           tech
2221  fast lifts rise into record books  two high-sp...           tech
2222  nintendo adds media playing to ds  nintendo is...           tech
2223  fast moving phone viruses appear  security fir...           tech
2224  hacker threat to apples itunes  users of apple...           tech

[2225 rows x 2 columns]

### Import spacy for other text cleaning purposes

In [66]:
! pip install spacy 

Defaulting to user installation because normal site-packages is not writeable


In [67]:
!python -m spacy download en_core_web_sm

Defaulting to user installation because normal site-packages is not writeable
     --------------------------------------- 12.8/12.8 MB 10.9 MB/s eta 0:00:00
[+] Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')


In [68]:
import spacy
nlp =spacy.load('en_core_web_sm')

### Remove Punctuations

In [69]:
df['data'] = df['data'].str.replace(',', ' ')
df['data'] = df['data'].str.replace('.', ' ')
df['data'] = df['data'].str.replace('-', ' ')
df['data'] = df['data'].str.replace('"', ' ')
df['data'] = df['data'].str.replace('  ',' ')

C:\Users\saiba\AppData\Local\Temp\ipykernel_7604\2653386819.py:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['data'] = df['data'].str.replace('.', ' ')


In [70]:
df

data         labels
0     musicians to tackle us red tape musicians grou...  entertainment
1     u2s desire to be number one u2 who have won th...  entertainment
2     rocker doherty in on stage fight rock singer p...  entertainment
3     snicket tops us box office chart the film adap...  entertainment
4     oceans twelve raids box office oceans twelve t...  entertainment
...                                                 ...            ...
2220  warning over windows word files writing a micr...           tech
2221  fast lifts rise into record books two high spe...           tech
2222  nintendo adds media playing to ds nintendo is ...           tech
2223  fast moving phone viruses appear security firm...           tech
2224  hacker threat to apples itunes users of apples...           tech

[2225 rows x 2 columns]

### Remove stop words 

In [71]:
stop_words = ['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 
              'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but',
               'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing',
               'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn',
               "hasn't", 'have', 'haven', "haven't", 'having', 'he', 'her', 'here', 'hers', 'herself', 'him', 'himself', 'his',
               'how', 'i', 'if', 'in', 'into', 'is', 'isn', "isn't", 'it', "it's", 'its', 'itself', 'just', 'll', 'm', 'ma', 'me',
               'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'now', 'o', 'of',
               'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan',
               "shan't", 'she', "she's", 'should', "should've", 'shouldn', "shouldn't", 'so', 'some', 'such', 't', 'than', 'that',
               "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', 'this', 'those', 'through',
               'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', 'were', 'weren', "weren't", 'what',
               'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y',
               'you', "you'd", "you'll", "you're", "you've", 'your', 'yours', 'yourself', 'yourselves']

In [72]:
def stop_word_removal(text):
    tokens = text.split(' ')
    words_without_stopwords = [x for x in tokens if x not in stop_words]
    final_sentence = ' '.join(words_without_stopwords)
    return final_sentence

In [73]:
df['clean_data'] = df['data'].apply(stop_word_removal)

In [74]:
df

data         labels  \
0     musicians to tackle us red tape musicians grou...  entertainment   
1     u2s desire to be number one u2 who have won th...  entertainment   
2     rocker doherty in on stage fight rock singer p...  entertainment   
3     snicket tops us box office chart the film adap...  entertainment   
4     oceans twelve raids box office oceans twelve t...  entertainment   
...                                                 ...            ...   
2220  warning over windows word files writing a micr...           tech   
2221  fast lifts rise into record books two high spe...           tech   
2222  nintendo adds media playing to ds nintendo is ...           tech   
2223  fast moving phone viruses appear security firm...           tech   
2224  hacker threat to apples itunes users of apples...           tech   

                                             clean_data  
0     musicians tackle us red tape musicians groups ...  
1     u2s desire number one u2 three prestigious gra...  
2     rocker doherty stage fight rock singer pete do...  
3     snicket tops us box office chart film adaptati...  
4     oceans twelve raids box office oceans twelve c...  
...                                                 ...  
2220  warning windows word files writing microsoft w...  
2221  fast lifts rise record books two high speed li...  
2222  nintendo adds media playing ds nintendo releas...  
2223  fast moving phone viruses appear security firm...  
2224  hacker threat apples itunes users apples music...  

[2225 rows x 3 columns]

In [75]:
!pip install vector embeddings

Defaulting to user installation because normal site-packages is not writeable


### Get the vector embeddings

In [77]:
def get_embeddings(text):
    doc = nlp(text)
    return doc.vector

In [78]:
df["embeddings"] = df["clean_data"].apply(get_embeddings)

In [79]:
df

data         labels  \
0     musicians to tackle us red tape musicians grou...  entertainment   
1     u2s desire to be number one u2 who have won th...  entertainment   
2     rocker doherty in on stage fight rock singer p...  entertainment   
3     snicket tops us box office chart the film adap...  entertainment   
4     oceans twelve raids box office oceans twelve t...  entertainment   
...                                                 ...            ...   
2220  warning over windows word files writing a micr...           tech   
2221  fast lifts rise into record books two high spe...           tech   
2222  nintendo adds media playing to ds nintendo is ...           tech   
2223  fast moving phone viruses appear security firm...           tech   
2224  hacker threat to apples itunes users of apples...           tech   

                                             clean_data  \
0     musicians tackle us red tape musicians groups ...   
1     u2s desire number one u2 three prestigious gra...   
2     rocker doherty stage fight rock singer pete do...   
3     snicket tops us box office chart film adaptati...   
4     oceans twelve raids box office oceans twelve c...   
...                                                 ...   
2220  warning windows word files writing microsoft w...   
2221  fast lifts rise record books two high speed li...   
2222  nintendo adds media playing ds nintendo releas...   
2223  fast moving phone viruses appear security firm...   
2224  hacker threat apples itunes users apples music...   

                                             embeddings  
0     [0.2015061, -0.20731805, -0.29421645, -0.03264...  
1     [0.28642786, -0.2850171, -0.10007215, -0.08766...  
2     [0.3285009, -0.24485895, -0.13713713, -0.08740...  
3     [0.21824618, -0.22423987, 0.031301666, 0.05396...  
4     [0.1465682, -0.23421904, 0.02751773, 0.0523804...  
...                                                 ...  
2220  [0.3579604, -0.124646805, -0.16185522, -0.1154...  
2221  [0.26983613, -0.12480863, -0.065554865, -0.099...  
2222  [0.25802773, -0.32408676, -0.06167393, -0.0253...  
2223  [0.3159842, -0.27449182, -0.049973343, -0.0783...  
2224  [0.16901626, -0.10892734, -0.10707976, -0.0015...  

[2225 rows x 4 columns]

In [80]:
df['embeddings'][0]

array([ 0.2015061 , -0.20731805, -0.29421645, -0.03264765,  0.21916921,
       -0.05042935,  0.5501444 ,  0.4307    ,  0.261175  , -0.16928634,
       -0.21529493,  0.09097307, -0.01081462, -0.19925919, -0.04118757,
        0.04806997, -0.27232245, -0.03489878,  0.22739677, -0.28044388,
       -0.1015219 ,  0.5330605 , -0.09791905,  0.15766653,  0.07064787,
       -0.34935203,  0.18186295,  0.49610642, -0.07337456, -0.10294759,
       -0.1465606 , -0.06178195, -0.26228082, -0.20223518, -0.17142998,
       -0.23332283, -0.02242098,  0.2706948 , -0.12008191, -0.15828232,
        0.08408713,  0.19633594, -0.12732959,  0.09826972,  0.05619971,
        0.28634807,  0.19533877,  0.07368031,  0.01499863, -0.25778034,
       -0.36234656,  0.01869481, -0.06841083, -0.42855462, -0.28193322,
       -0.07975227,  0.2289588 ,  0.00552694, -0.01924665,  0.11472248,
       -0.10690436,  0.05169892, -0.00837729, -0.21983337,  0.03722552,
        0.15396802,  0.3769077 ,  0.11493958, -0.05340163, -0.23

In [81]:
np.vstack(df["embeddings"].values).shape

(2225, 96)

In [50]:
classes=df['labels'].unique()
classes

array(['entertainment', 'business', 'sport', 'politics', 'tech'],
      dtype=object)

In [82]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(classes)

LabelEncoder()

In [83]:
df['Encoded_labels'] = le.transform(df['labels'])
df.tail()

data labels  \
2220  warning over windows word files writing a micr...   tech   
2221  fast lifts rise into record books two high spe...   tech   
2222  nintendo adds media playing to ds nintendo is ...   tech   
2223  fast moving phone viruses appear security firm...   tech   
2224  hacker threat to apples itunes users of apples...   tech   

                                             clean_data  \
2220  warning windows word files writing microsoft w...   
2221  fast lifts rise record books two high speed li...   
2222  nintendo adds media playing ds nintendo releas...   
2223  fast moving phone viruses appear security firm...   
2224  hacker threat apples itunes users apples music...   

                                             embeddings  Encoded_labels  
2220  [0.3579604, -0.124646805, -0.16185522, -0.1154...               4  
2221  [0.26983613, -0.12480863, -0.065554865, -0.099...               4  
2222  [0.25802773, -0.32408676, -0.06167393, -0.0253...               4  
2223  [0.3159842, -0.27449182, -0.049973343, -0.0783...               4  
2224  [0.16901626, -0.10892734, -0.10707976, -0.0015...               4

In [84]:
pd.set_option('display.max_colwidth',300)
df[['Encoded_labels','labels']].drop_duplicates()

Encoded_labels         labels
0                  1  entertainment
386                0       business
896                3          sport
1407               2       politics
1824               4           tech

In [95]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
x = np.vstack(df["embeddings"].values)
y = df["Encoded_labels"]

In [100]:
model = RandomForestClassifier(random_state=42)
from sklearn.model_selection import cross_val_score
scores = cross_val_score(model, x, y, cv=6)
print(scores)
print("Mean CV accuracy: ",np.mean(scores))

[0.76280323 0.70889488 0.73315364 0.69272237 0.7115903  0.65945946]
Mean CV accuracy:  0.7114373133241059


In [98]:
from sklearn.tree import DecisionTreeClassifier
model2=DecisionTreeClassifier(criterion='gini',random_state=42)
scores=cross_val_score(model2,x,y,cv=6)
print(scores)
print("Mean CV accuracy: ",np.mean(scores))

[0.54177898 0.52830189 0.56334232 0.53908356 0.58760108 0.56486486]
Mean CV accuracy:  0.5541621135960759


In [99]:
from sklearn.neighbors import KNeighborsClassifier
model3 = KNeighborsClassifier(n_neighbors=11)
scores = cross_val_score(model3, x, y, cv=6)
print(scores)
print("Mean CV accuracy: ",np.mean(scores))

[0.74123989 0.67115903 0.70080863 0.63881402 0.69272237 0.62432432]
Mean CV accuracy:  0.678178043272383
